### ISSUE TITLE
Additional markdown features

### ISSUE THREAD

**Issue by mvuorre** [crsh/qapaja#3]
Separating this from #1.

As I see it papaja/bookdown [currently provides the following](https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html), some of which are already part of core Quarto:

- [X] Number and reference equations
    - https://quarto.org/docs/authoring/cross-references.html#equations
- [X] Theorems and proofs
    - https://quarto.org/docs/authoring/cross-references.html#theorems-and-proofs
- [ ] Special headers 
    - Not needed (some functionality exists in Quarto (e.g. numbered/unnumbered)
- [X] Appendices
    - https://quarto.org/docs/authoring/appendices.html#custom-appendix-sections 
- [ ] #6
    - Maybe a later feature?

**Comment by crsh** [comment]
So I would say, we don't need chapter headings like in **bookdown**, but appendices are important. Those are already implemented: https://quarto.org/docs/authoring/appendices.html#custom-appendix-sections

For text-references, maybe [Quarto variables](https://quarto.org/docs/authoring/variables.html) can be used. One thing I still need to test is whether these can also be inserted inside code chunks (to define captions, for example), and in side the YAML front matter, e.g., to have results in the abstract, as outlined [here](https://fediscience.org/@FrederikAust/109358961545665168). @mvuorre was this what you had in mind?

**Comment by mvuorre** [comment]
You can already write abstracts later on and reference R variables:
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/7349270/203395346-d32cd44b-6217-44f8-9037-3efc6639dd3e.png">

There is also this extension/shortcode: https://github.com/pandoc-ext/abstract-section

There are probably some ways in core Quarto to include text references [like](https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#text-references) "(ref:foo) Define a text reference **here**. " but I don't know how it would work immediately. I'd say they are an optional nice to have, but not essential. Maybe we can close this as complete and let that hang in another issue?

**Comment by crsh** [comment]
I agree this is not essential and could go in its own issue. That said, I'm not sure I love the solution to put the abstract somewhere after the result section of a manuscript. I would hate having to search for the abstarct in my documents. ;) I guess another solution is to cache the chunk and use `knitr::load_cache()`, but this has always been a little unsatisfactory to me. Anyway, new issue. :)

**Comment by mvuorre** [comment]
It also doesn't look nice in the RStudio outline panel 😢 but is "good enough" for now I suppose.
